[Theme]
DisplayName=-_ A e s t h e t i c _-

[Control Panel\Desktop]
Wallpaper=DesktopBackground\0.jpeg
TileWallpaper=0
WallpaperStyle=10
Pattern=

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
ColorizationColor=0XFF000000
Transparency=1
Composition=1
VisualStyleVersion=10

[Slideshow]
Interval=300000
Shuffle=1
ImagesRootPath=DesktopBackground

[MasterThemeSelector]
MTSM=DABJDKT


















